version: "3"

services:
  http:
    build:
      context: ./http
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./magento:/var/www/html/magento
    ports:
      - 8383:80

  mysql:
    image: mariadb:10
    restart: always
    ports:
      - "3309:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8484:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=100M